name: deploy

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy
        run: |
              argocd login 10.89.0.2:31423 --insecure --username ${{ secrets.ARGO_USER }} --password ${{ secrets.ARGO_PASS }}
        env:
          ARGO_USER: ${{ secrets.ARGO_USER }}
          ARGO_PASS: ${{ secrets.ARGO_PASS }}
              
