name: deploy

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy
        run: |
              argocd login 10.89.0.2:31423 --insecure --username "${env.user}" --password "${env.pass}"
        env:
          GIT_USERNAME: ${{ secrets.ARGO_USER }}
          GIT_PASSWORD: ${{ secrets.ARGO_PASS }}
              
